theme: minima
title: Lily's Website :)
author: Lily Xing
email: lxing1@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my website
# social links
github_username:  lilyxing0
tiktok_username:  abcdefghijklilyz
snapchat_username:  lilyxing2016

show_excerpts: true # set to false to remove excerpts on the homepage
